/* Minimal neutral <stdlib.h> matching the Digital Research C run-time ABI.
   strtol is NOT in DR C (pre-ANSI) and is supplied by cpmlibc.c.

   malloc/calloc/realloc return `char *`, NOT the ANSI `void *`: DR C 1.11 is
   pre-ANSI (K&R) and its runtime returns char*. The cc-cpm86 target auto-
   includes _preincl.h (generated by install-cpm86-target.sh from CLEAR*.L86),
   which declares these as `extern char *malloc()` + a DRC_PTR pragma pinning the
   far BX:AX return register. char* and void* are register-identical on this ABI,
   so this is purely a type-checking match -- declaring void* here made Watcom
   reject every module with E1062 "Inconsistent return type for function
   'malloc'" against the auto-included char* decl. Upstream stdcbench src assigns
   the result to typed pointers, which char* satisfies here without edits. */
#ifndef _CPM_STDLIB_H
#define _CPM_STDLIB_H
#include <stddef.h>

/* Provided by DR C (clears.l86) */
char  *malloc(size_t);
char  *calloc(size_t, size_t);
char  *realloc(void *, size_t);
void   free(void *);
int    atoi(const char *);
int    abs(int);
void   qsort(void *, size_t, size_t, int (*)(const void *, const void *));
void   exit(int);

/* Supplied by cpmlibc.c (missing from DR C) */
long   strtol(const char *, char **, int);

#endif
